# Generated by Django 5.1 on 2024-09-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
