# Generated by Django 5.1 on 2024-09-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='publicada',
        ),
    ]
