# Generated by Django 5.1 on 2024-09-09 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_remove_receta_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='megusta',
            name='publicacion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='recetas.receta'),
        ),
        migrations.AddField(
            model_name='megusta',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='megusta_set', to='recetas.receta'),
        ),
    ]
